script:
 -"bundle exec rake neo4j:install['community-2.2.0-M02'] neo4j:start default --trace"
language: ruby
rvm:
 - 2.0.0
before_deploy: "echo ready? =============="
deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  cleanup: true

