deploy:
provider: releases
api_key:
secure: "sLxHZQVNJ9RUvCp7qKCP+sU9AcavgJjFdvG9QAHlo6HxQus9ys+qi39GkdsngRe7ICR4Rp0ELlAI508SRdP7QoP6EmiAYxkDwLiXrT9fCiB4nefMCc3anrqs1bR4vXQLp/CwFWo+q7c3/jN4TmIKE70gHpeAJJwn5eKJKTKyWD7b1poBQFinntc9HoyaJSOjxps8lhD9Y8jqzHK6Z0QNBwkXnP+G320DhXxBtt0XtuSPmbTqmRmPCKlyhAUI3QKwS7fPOZxb8CTsApwp5jOlhVkN2lg7Ops2NEgNqe8r5xG3tvjCBC6CgpTeT4MiRqHB7XgGJB4ZXuAtB7uT1WtBFoF8ZkkrTB7JHLaNRhvqoO18jkaQyCBf7Yc3B81FkRFfGZ8kfm5LaPuTEVZY6lWLu9hQdaULN+2iCIy5WNqJ6Bn88hgf/1Zgifjrp+1YW8lFRQHODTONRI400UMOFyQjo9yu7DLtUvKbGhN3xRJ2MgL5AhJtTc0ejAjER1BxLBTKKgxYGTdKLo0UxntmM9eL8QVVs7yurz9VtEpvud8wxpVseI2xtvV9sNSgH/i5T7UWvQiJX8I+Pf9K4UYmLBk63x0Ewnd7ZJZKAUyscvNmvCSQxSWcTTpLOHZGM4g5SGLR7MZC+VDp2w0zMHdjXIPITOthuGk3GZmOBYVJvGacKals="
file_glob: true
file: *.tar.gz
skip_cleanup: true
on:
tags: true
