language: node_js # 升级版本需要依赖 npm
node_js: stable

install: true # 用来指定安装脚本， 无需安装依赖，true 跳过安装

branches:
  only:
  - master # 只发布 master 分支

before_script:
- git config --global user.name "weichanglu" # 配置 travis git 信息
- git config --global user.email "cl9000@126.com"

script: # 指定构建或测试运行脚本
- git push -f $GH_URL `npm version patch -m "%s [ci skip]"` # 打 Tag，发布到 Github Release, 使用 [ci skip] 跳过 CI， 防止死循环
- git push -f $GH_URL HEAD:master #将新版本文件推送回 Github


deploy:
  provider: releases
  api_key:
    secure: "sLxHZQVNJ9RUvCp7qKCP+sU9AcavgJjFdvG9QAHlo6HxQus9ys+qi39GkdsngRe7ICR4Rp0ELlAI508SRdP7QoP6EmiAYxkDwLiXrT9fCiB4nefMCc3anrqs1bR4vXQLp/CwFWo+q7c3/jN4TmIKE70gHpeAJJwn5eKJKTKyWD7b1poBQFinntc9HoyaJSOjxps8lhD9Y8jqzHK6Z0QNBwkXnP+G320DhXxBtt0XtuSPmbTqmRmPCKlyhAUI3QKwS7fPOZxb8CTsApwp5jOlhVkN2lg7Ops2NEgNqe8r5xG3tvjCBC6CgpTeT4MiRqHB7XgGJB4ZXuAtB7uT1WtBFoF8ZkkrTB7JHLaNRhvqoO18jkaQyCBf7Yc3B81FkRFfGZ8kfm5LaPuTEVZY6lWLu9hQdaULN+2iCIy5WNqJ6Bn88hgf/1Zgifjrp+1YW8lFRQHODTONRI400UMOFyQjo9yu7DLtUvKbGhN3xRJ2MgL5AhJtTc0ejAjER1BxLBTKKgxYGTdKLo0UxntmM9eL8QVVs7yurz9VtEpvud8wxpVseI2xtvV9sNSgH/i5T7UWvQiJX8I+Pf9K4UYmLBk63x0Ewnd7ZJZKAUyscvNmvCSQxSWcTTpLOHZGM4g5SGLR7MZC+VDp2w0zMHdjXIPITOthuGk3GZmOBYVJvGacKals="
# secure: ${GH_TOKEN}

file: *.tar.gz
file_glob: true
skip_cleanup: true
on:
  tags: false